# Font
font_family Maple Mono Italic

# Cursor
shell_integration no-cursor
cursor_shape beam

# Padding
window_padding_width 7
window_padding_height 10

# Scrollback
scrollback_lines 3000

# Font size
font_size 11

# Resize shortcuts
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Opacity
background_opacity 0.86


# ------------------------------------------------------------
# Pixel Ocean High-Contrast theme
# Blue ocean base, readable cyan folders, pink accents
# ------------------------------------------------------------

cursor               #ff4fa3
cursor_text_color    #0b1020

selection_background #3b82f6
selection_foreground #f4fbff

background           #0b1020
foreground           #e6f3ff

# black / bright black
color0               #101827
color8               #536179

# red / bright red
color1               #ff4fa3
color9               #ff7ab8

# green / bright green
color2               #7ee787
color10              #9fffa8

# yellow / bright yellow
color3               #ffd166
color11              #ffe08a

# blue / bright blue
color4               #4db8ff
color12              #7ccfff

# magenta / bright magenta
color5               #ff5faf
color13              #ff8ac6

# cyan / bright cyan
color6               #5eead4
color14              #9ffcf0

# white / bright white
color7               #d8f3ff
color15              #ffffff
